//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string Names { get; set; }
        public string Links { get; set; }
        public Nullable<int> Pioriti { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
