//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Customer { get; set; }
        public string Phone { get; set; }
        public string Emails { get; set; }
        public string Amount { get; set; }
        public string Note { get; set; }
    }
}
